sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 111
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tDtRURimF517DSyjVdy
    access-key-secret: 6CKk8VpED6eoYDJoKpd25rbyXvW36s
    bucket-name: sky-cty-itcast
  redis:
    host: localhost
    port: 6379
    password: 111
    database: 10
